name: Build and Release GKI Kernel with KernelSU & SUSFS

on:
  push:
    branches:
      - main  # 或者你希望触发构建的分支
  pull_request:
    branches:
      - main  # 在PR到main时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up dependencies
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            binutils-dev \
            bison \
            build-essential \
            ca-certificates \
            ccache \
            clang \
            cmake \
            curl \
            file \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            lld \
            make \
            ninja-build \
            python3-dev \
            texinfo \
            u-boot-tools \
            xz-utils \
            zlib1g-dev \
            gcc-aarch64-linux-gnu \
            clang


      # Step 3: Set up SSH (if you need SSH keys to clone private repos)
      # Uncomment the following block if you use SSH for private repositories
      # - name: Set up SSH keys
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Run the build script
      - name: Run build script
        run: |
          chmod +x ./scripts/aio_gki_build_kernel_release.sh
          ./scripts/aio_gki_build_kernel_release.sh

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./builds/**/*

      # Step 6: Create GitHub Release
      - name: Create GitHub Release
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          ./scripts/create_github_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
